server.port=8080
spring.application.name=novel-reader
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
app.novel-data-path=./novel-data/novels.json
app.novel-storage-path=./novel-storage/